# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myverysecretpassword
      MYSQL_DATABASE: users
      MYSQL_USER: spring
      MYSQL_PASSWORD: mysecretpassword
    ports:
      - "1000:3306"
    volumes:
      - ./dbdata:/var/lib/mysql

